
http://dummy.restapiexample.com/api/v1/employee/90773

###
http://dummy.restapiexample.com/api/v1/employee/90773

###
http://dummy.restapiexample.com/api/v1/update/

###
http://dummy.restapiexample.com/api/v1/delete/

###
http://dummy.restapiexample.com/api/v1/create






